"""Instrument and strategy domain models for Nifty F&O backtesting."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Literal


class InstrumentType(str, Enum):
    SPOT = "spot"
    FUTURE = "future"
    OPTION = "option"


class OptionType(str, Enum):
    CALL = "CE"
    PUT = "PE"


class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"

    @property
    def sign(self) -> int:
        return 1 if self is Side.BUY else -1


ExpiryBucket = Literal["weekly", "monthly", "next_month", "next_to_next_month"]


@dataclass(frozen=True, slots=True)
class Instrument:
    """A normalized tradable instrument reference."""

    instrument_type: InstrumentType
    side: Side
    quantity: int
    expiry_bucket: ExpiryBucket = "monthly"
    option_type: OptionType | None = None
    strike_offset_pct: float = 0.0
    symbol: str = "NIFTY"

    @property
    def label(self) -> str:
        if self.instrument_type is InstrumentType.FUTURE:
            return f"{self.symbol} FUT {self.expiry_bucket} {self.side.value.upper()}"
        if self.instrument_type is InstrumentType.OPTION:
            return (
                f"{self.symbol} {self.option_type.value if self.option_type else ''} "
                f"{self.expiry_bucket} {self.side.value.upper()} {self.strike_offset_pct:+.2f}%"
            )
        return f"{self.symbol} SPOT"


@dataclass(frozen=True, slots=True)
class TriggerRule:
    """Entry trigger based on a percentage move from a reference spot level."""

    move_pct: float = 1.0
    direction: Literal["up", "down", "both"] = "up"
    no_repeat_levels: bool = True


@dataclass(frozen=True, slots=True)
class StrategyDefinition:
    """Structured strategy generated by the natural-language parser."""

    name: str
    description: str
    legs: tuple[Instrument, ...]
    trigger: TriggerRule = field(default_factory=TriggerRule)
    rollover_after_day: int = 15
    square_off_on_expiry: bool = True
    initial_capital: float = 1_000_000.0
    lot_size: int = 50
    margin_per_lot: float = 150_000.0
